settings:
  title: 'Uptime Bot'
  url: 'https://uptime_bot-production.100srgb.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: whrblog_online # unique identifier
    name: Hello Traveler 🗺
    description: 'Sometimes ever, sometimes never' # default=empty
    url: 'https://whrblog.online' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Synology Nas
    name: Synology Nas 💾
    description: ''
    url: 'https://synology.whrblog.online:5001'
    method: PING
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

